# This workflow is managed by gh actions-lock.
# SPDX-License-Identifier: MPL-2.0
name: Release
on:
  push:
    tags:
      - 'v*'
permissions: read-all
jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4.3.1
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2.5.0
        with:
          files: |
            docs/whitepapers/academic/snif.pdf
